# Generated by Django 3.2.9 on 2021-11-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repository', '0002_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='repo',
            new_name='repo_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user',
            new_name='user_id',
        ),
    ]
