# Generated by Django 3.2.9 on 2021-11-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Repository', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('submit_info', models.CharField(max_length=100)),
                ('request_id', models.IntegerField()),
                ('check_time', models.DateTimeField(auto_now=True)),
                ('result', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('checkMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repository.member')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_info', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
                ('deadline', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repository.member')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.record')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Repository.repository')),
            ],
        ),
    ]
