# Generated by Django 3.2.9 on 2021-11-11 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Repository', '0002_member'),
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='submitMember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submit', to='Repository.member'),
        ),
        migrations.AlterField(
            model_name='record',
            name='checkMember',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checking', to='Repository.member'),
        ),
        migrations.AlterField(
            model_name='record',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='result',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.record'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
