# Generated by Django 3.2.9 on 2021-11-13 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_auto_20211111_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='Task.task'),
        ),
    ]
