# Generated by Django 3.2.6 on 2021-11-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_record_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='task', max_length=100),
        ),
    ]
