# Generated by Django 3.2.6 on 2021-11-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_task_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
