# Generated by Django 3.2.9 on 2021-11-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
